# Generated by Django 4.0.6 on 2022-08-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_is_active_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
